Vagrant.configure(2) do |config|
  config.vm.box = "jasonc/centos7"
  config.vm.hostname = "testbox01"
  config.vm.network "private_network", ip: "10.9.8.7"
  config.vm.provider "virtualbox" do |vb|
	vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
  end
end
